### ISSUE TITLE
"acl" or "xcomp"

### ISSUE THREAD

**Issue by bencampbell30** [UniversalDependencies/UD_German-GSD#1]
When going through the treebank, I found two sentences with identical structures that were annotated differently:
#35: **Der Friseursalon ist mit dem Bus sehr gut zu erreichen** .
#290: **Die Tanzschule ist mit öffentlichen Verkehrsmitteln gut zu erreichen** und für Autofahrer stehen viele kostenlose Parkplätze zu der Verfügung .

In #35, "erreichen" is a dependent of "ist", with dependency "acl".

In #290, "erreichen" is a dependent of "ist" with dependency "xcomp".

Which is correct?

**Comment by dan-zeman** [comment]
Unfortunately the treebank is not annotated consistently. I found at least two other analyses in addition to the two quoted above. I doubt whether _erreichen_ should depend on _ist_ in the first place. It would make more sense to me to make _erreichen_ the head in UD. But if it is attached as dependent of _ist_, then it definitely should not be `acl`, which stands for "adnominal clause" and should not be attached to verbs. `xcomp` would be better.

**Comment by dan-zeman** [comment]
Fixed: _erreichen_ is now the head, _ist_ depends on it as `cop`.
