### ISSUE TITLE
Fix punctuation attachment

### ISSUE THREAD

**Issue by simon-clematide** [UniversalDependencies/UD_German-GSD#20]
The punctuation attachment of GSD is not conforming to the guidelines. Applying the udapy fixpunct script would improve the situation a lot and works well (according to some eyeballing of the results).

I am not fluent with the UD German commit policy (apply it on dev and create pull request), maybe it is easier if a contributor applies the fix punct script.
http://stp.lingfil.uu.se/pipermail/ud/2017-October/000455.html

**Comment by dan-zeman** [comment]
Thanks, fixed.
