### ISSUE TITLE
Contradictory XPOS and Feats in verbs

### ISSUE THREAD

**Issue by kanayamah** [UniversalDependencies/UD_German-GSD#25]
There are many contradictory XPOS and features.  In most of cases, XPOS seems to be correct.

|XPOS|VerbForm|freq|grew link|
|---|---|---:|---|
|VVFIN|Inf|94|http://match.grew.fr/?corpus=UD_German-GSD@2.9&custom=621395f8d9962|
|VVFIN|Part|50|http://match.grew.fr/?corpus=UD_German-GSD@2.9&custom=62139788491eb|
|VVPP|Inf|19|http://match.grew.fr/?corpus=UD_German-GSD@2.9&custom=621396a5a0d92|
|VVPP|Fin|42|http://match.grew.fr/?corpus=UD_German-GSD@2.9&custom=6213972c5bef1|
|VVINF|Fin|31|http://match.grew.fr/?corpus=UD_German-GSD@2.9&custom=62139b3a848c6|
|VVINF|Part|5|http://match.grew.fr/?corpus=UD_German-GSD@2.9&custom=621397cee9b30|

**Comment by dan-zeman** [comment]
Thanks! Fixed in dev.
