### ISSUE TITLE
Inconsistent lemma of "nächste"

### ISSUE THREAD

**Issue by kanayamah** [UniversalDependencies/UD_German-GSD#28]
In v2.9, `nächste`'s lemma is inconsistent (`nah`: 51 cases vs. `nächster`: 8 cases), and `nächster` looks awkward as an adjective's lemma.
http://universal.grew.fr/?corpus=UD_German-GSD@2.9&custom=62441b5303f54&clustering=N.lemma

In my PR #27, I intentionally did not add `Degree=Sup` for these cases.
There are three options to keep the annotations consistent:
* make the lemma `nächste` (I recommend this)
* make the lemma `nah`, and change `Degree=Pos` to `Degree=Sup`
* annotate them depending on context

**Comment by dan-zeman** [comment]
I would say that the second option is the best, i.e., lemma = _nah_ and `Degree=Sup`.
