### ISSUE TITLE
Annotation help

### ISSUE THREAD

**Issue by fhennig** [UniversalDependencies/UD_German-GSD#6]
The whole sentence is: "Die Fertigungsstätte in Dresden reserviert AMD offenbar für die kommenden, auf Kupfer-Layern beruhenden Athlons."

The relevant part is "auf Kupfer-Layern beruhenden", how would that be attached to "Athlons"?

**Comment by amir-zeldes** [comment]
I'd say amod(Athlons, beruhenden)

**Comment by dan-zeman** [comment]
Another possibility is `acl(Athlons, beruhenden)` (on the grounds that participles are verbs and thus constitute clauses).

I feel a bit more comfortable with the `amod` analysis but I haven't checked what's elsewhere in the German data, and it should be done consistently.

**Comment by fhennig** [comment]
Okay so my first though was also amod, and then obl and case for the other two words. It was just off-putting that in my source treebank the 'auf Kupfer-Layern' was attached as an OBJP, so a kind of object to the adjective. It makes sense, because the participle has verbal elements to it. It just feels weird to attach something as a modifier which is actually more of an object. The 'auf Kupfer-Layern' cannot be left out, 'beruhenden' by itself does not make sense, as such 'auf Kupfer-Layern' is not simply a modifier.  Now that I see the similary to verb words, I think I've already read something about this. There are other words which require an object like 'to resort to something', where the 'to something' would be attached as obl as well. This is more prevalent in german I think, and that might be why I'm more inclined to see these as objects.

**Comment by amir-zeldes** [comment]
Absolutely, and I think this happens in German even with non-participial adjectives, for example ähnlich "similar"+ ARG. It's pretty rare in attributive position, but here's an example from DEWAC:

Jetzt erinnerte sie sich an den **einem Wiegenlied ähnlichen** Sprechgesang , den sie im Traum gehört hatte
Lit.: _"Now she remembered the **to a lullaby similar** speech melody, which she'd heard in the dream"_

**Comment by dan-zeman** [comment]
I am closing this as it does not seem to point at a bug in the GSD treebank.
